//
// Example.idl 
//
import "oaidl.idl"; 
[
object, dual, oleautomation,
uuid(a03d1420-b1ec-11d0-8c3a-00c04fc31d2f),
] interface ITestLongCollection : IDispatch
{
    [id(1),propget]
    HRESULT Count([out,retval] long* cnt);

    [id(2)]
    HRESULT Item([in] long index, [out,retval] long* cnt);

};
 
[
uuid(a03d1423-b1ec-11d0-8c3a-00c04fc31d2f),
version(1.0),
helpstring("Example Type Library"),
] library ExampleLib
{
  importlib("stdole32.tlb");
  [
  uuid(a03d1424-b1ec-11d0-8c3a-00c04fc31d2f),
  helpstring("Breakfast Component Class")
  ] coclass MyLongCollection
    {
    [default]interface ITestLongCollection;
    }; //end coclass def

}; //end library def