#define MTLEDITOR_IMTLEDITORDOCUMENT_DOCUMENTID 1
#define MTLEDITOR_IMTLEDITORDOCUMENT_FILENAME 2
#define MTLEDITOR_IMTLEDITORDOCUMENT_CONTENT 3
#define MTLEDITOR_IMTLEDITORDOCUMENTS_COUNT 1
#define MTLEDITOR_IMTLEDITORDOCUMENTS_ITEM 2
#define MTLEDITOR_IMTLEDITORDOCUMENTS_REMOVE 3
#define MTLEDITOR_IMTLEDITOR_SAYHELLO 1
#define MTLEDITOR_IMTLEDITOR_VALUE 2
#define MTLEDITOR_IMTLEDITOR_DOCUMENTS 3
#define MTLEDITOR_IMTLSCRIPTHOSTOBJECT_IMPORT 2
#define MTLEDITOR_IMTLSCRIPTHOSTOBJECT_SETTIMEOUT 3
#define MTLEDITOR_IMTLSCRIPTHOSTOBJECT_WAIT 4
#define MTLEDITOR_IMTLSCRIPTHOSTOBJECT_QUIT 5
#define MTLEDITOR_IMTLSCRIPTHOSTOBJECT_CREATEOBJECT 6
#define MTLEDITOR_IMTLSCRIPTHOSTOBJECT_WINRT 7

